run:
  timeout: 10m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats: 
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  govet:
    enable:
      - shadow
  
  revive:
    min-confidence: 0.8
  
  gocyclo:
    min-complexity: 15
  
  dupl:
    threshold: 100
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  misspell:
    locale: US
  
  lll:
    line-length: 140
  
  goimports:
    local-prefixes: github.com/pprofio/pprofio
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
    disabled-checks:
      - whyNoLint
      - unnamedResult
      - hugeParam  # Allow large config structs for now
  
  funlen:
    lines: 80
    statements: 40
  
  gocognit:
    min-complexity: 20
  
  nestif:
    min-complexity: 5
  
  wsl:
    strict-append: true
    allow-assign-and-call: true
    allow-multiline-assign: true
    allow-cuddle-declarations: false
    allow-trailing-comment: false
    force-case-trailing-whitespace: 0
  
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/pprofio/pprofio
        deny:
          - pkg: "github.com/google/uuid"
            desc: "Use crypto/rand or a more secure UUID generator"

linters:
  enable:
    - bodyclose
    - unused
    - depguard
    - dogsled
    - dupl
    - errcheck
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
  
  disable:
    - gochecknoglobals  # We may need some global vars for profiler configuration
    - copyloopvar      # Requires Go 1.22+

issues:
  uniq-by-line: true
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - dupl
        - gosec
        - funlen
        - goconst
        - wsl
    
    # Exclude specific false positives
    - path: examples/
      linters:
        - errcheck
        - gosec
    
    # Exclude known issues in third-party imports
    - path: vendor/
      linters:
        - all
  
  exclude:
    # Ignore "Error return value of .* is not checked" for defer statements
    - Error return value of `.*\.Close` is not checked
    
    # Ignore specific false positives
    - "G404: Use of weak random number generator"  # We use crypto/rand where needed
    
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: "" 